tag_checker:
  stage: build
  script:
    - python tag_checker.py $CI_COMMIT_TAG
  only:
    - tags

junit:
  stage: test
  script:
    - sbt test
    
#sonarqube_master_job:
#  stage: test
#  only:
#    - master
#  script:
#    - sonar-scanner -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID
#https://github.com/gabrie-allaigre/sonar-gitlab-plugin/

recent-artifacts:
  stage: deploy
  script:
    - sbt dist
  artifacts:
    paths:
      - target/universal/*.zip
    expire_in: 1 week
  except:
    - tags

release-artifacts:
 stage: deploy
 script:
    - sbt dist
 artifacts:
    paths:
    - target/universal/*.zip
 only:
    - tags
    

